### PR TITLE
Add directory_visibility config

### PR DESCRIPTION
**Pull request by mynameisbogdan**
Adapters are using `$config->get(Config::OPTION_DIRECTORY_VISIBILITY)` but currently isn't configurable from the bundle. This PR indents to fix that.

### CODE REVIEW

**Comment by mynameisbogdan** [comment]
I'm already using this PR in production, any chance to be accepted? 

kindly ping @tgalopin

**Comment by brusch** [comment]
Stumbled upon this as well, would be a very nice addition!

**Comment by tgalopin** [comment]
Hey @mynameisbogdan !

Sorry for the delayed answer. Could you add tests? Otherwise this seems like a good addition :) .

**Comment by mynameisbogdan** [comment]
Hello @tgalopin!

I added some visibility tests but the `visibility` method when called for a private directory returns `public`.  

See the following:
```
class League\Flysystem\DirectoryAttributes#5354 (4) {
  private $type =>
  string(3) "dir"
  private $path =>
  string(12) "path-private"
  private $visibility =>
  string(6) "public"
  private $lastModified =>
  int(1621769406)
}
```

Screenshot 2021-05-23 at 14 43 37

**Comment by mynameisbogdan** [comment]
Kindly ping @tgalopin

**Comment by mturalenka** [comment]
any chance this to be resolved?

**Pull request closed without merging**
