### PR TITLE
Adding storage name on flysystem.storage tag

### PR DESCRIPTION
**Pull request by johndodev**
Allowing to use that feature : https://symfony.com/blog/new-in-symfony-4-3-indexed-and-tagged-service-collections

### CODE REVIEW

**Comment by tgalopin** [comment]
It would be great to have a test for this (in Symfony 4.3+). I'm thinking about a kernel test (https://github.com/thephpleague/flysystem-bundle/tree/master/tests/Kernel) but where a service locator is created and extracted in the test to ensure it does contain the proper services.

Do you think you could have time to add this test :) ?

**Comment by johndodev** [comment]
I don't know how to do that, I used to unit tests. if you already have in mind what you need you will be more efficient than me.

**Comment by tgalopin** [comment]
I'll have a look :)

**Comment by tgalopin** [comment]
Thanks @johndodev ! I'll add tests and use this feature in the new Lazy adapter i'm working on to implement DSN configuration, your issue was very helpful!

**Comment by johndodev** [comment]
Pleasure !

**Pull request merged**
