### PR TITLE
Encourage the use of "league/flysystem-sftp-v3" instead of "league/fl…

### PR DESCRIPTION
**Pull request by maxhelias**
…ysystem-sftp"

### CODE REVIEW

**Comment by maxhelias** [comment]
related to https://github.com/thephpleague/flysystem/issues/1261

**Comment by maxhelias** [comment]
friendly ping @tgalopin 😃

**Comment by tgalopin** [comment]
The PHP 7.2 / Symfony 4.4 tests are failing, I guess because the version installed if probably old. Maybe it's time to release a new major dropping support for EOL tools. WDYT?

**Comment by maxhelias** [comment]
Oh I didn't pay attention to the CI in 7.2. It's related to the version of flysystem which had a bad configuration of the .gitatttributes in 2.0.0 and still includes phpseclib v2

**Comment by maxhelias** [comment]
Not necessarily need to drop support now but I'm always for that kind of thing, I can work on it on another PR

**Comment by tgalopin** [comment]
Thanks for the fix :) ! Merging

**Comment by tgalopin** [comment]
If you wish to open a PR for Symfony 6.1+ and PHP 8.1+, that would be great :) !

**Pull request merged**
